services:
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - 4000:4000
      - 9229:9229
    develop:
      watch: #remplace l'option volumes (de docker-compose.yml)
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend/package.json

  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - 3000:3000
    develop:
      watch: #remplace l'option volumes (de docker-compose.yml)
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: ./frontend/package.json
